version: '3.7'

x-icinga-db-web-config:
  &icinga-db-web-config
  icingaweb.modules.icingadb.config.icingadb.resource: icingadb
  icingaweb.modules.icingadb.redis.redis1.host: icingadb-redis
  icingaweb.modules.icingadb.redis.redis1.port: 6379
  icingaweb.modules.icingadb.commandtransports.icinga2.host: icinga2
  icingaweb.modules.icingadb.commandtransports.icinga2.port: 5665
  icingaweb.modules.icingadb.commandtransports.icinga2.password: icingawebpass
  icingaweb.modules.icingadb.commandtransports.icinga2.transport: api
  icingaweb.modules.icingadb.commandtransports.icinga2.username: icingaweb
  icingaweb.resources.icingadb.charset: utf8
  icingaweb.resources.icingadb.db: pgsql
  icingaweb.resources.icingadb.dbname: icingadb
  icingaweb.resources.icingadb.host: icinga-postgres
  icingaweb.resources.icingadb.password: pgpassword!
  icingaweb.resources.icingadb.type: db
  icingaweb.resources.icingadb.username: postgres

x-icinga-director-config:
  &icinga-director-config
  icingaweb.modules.director.config.db.resource: director
  icingaweb.modules.director.kickstart.config.endpoint: icinga2
  icingaweb.modules.director.kickstart.config.host: icinga2
  icingaweb.modules.director.kickstart.config.port: 5665
  icingaweb.modules.director.kickstart.config.username: icingaweb
  icingaweb.modules.director.kickstart.config.password: ${ICINGAWEB_ICINGA2_API_USER_PASSWORD:-icingaweb}
  icingaweb.resources.director.charset: utf8
  icingaweb.resources.director.db: pgsql
  icingaweb.resources.director.dbname: director
  icingaweb.resources.director.host: icinga-postgres
  icingaweb.resources.director.password: pgpassword!
  icingaweb.resources.director.type: db
  icingaweb.resources.director.username: director

x-icinga-web-config:
  &icinga-web-config
  icingaweb.authentication.icingaweb2.backend: db
  icingaweb.authentication.icingaweb2.resource: icingaweb
  icingaweb.config.global.config_backend: db
  icingaweb.config.global.config_resource: icingaweb
  icingaweb.config.global.module_path: /usr/share/icingaweb2/modules
  icingaweb.config.logging.log: php
  icingaweb.groups.icingaweb2.backend: db
  icingaweb.groups.icingaweb2.resource: icingaweb
  icingaweb.passwords.icingaweb2.icingaadmin: icinga
  icingaweb.resources.icingaweb.charset: utf8
  icingaweb.resources.icingaweb.db: pgsql
  icingaweb.resources.icingaweb.dbname: icingaweb
  icingaweb.resources.icingaweb.host: icinga-postgres
  icingaweb.resources.icingaweb.password: pgpassword!
  icingaweb.resources.icingaweb.type: db
  icingaweb.resources.icingaweb.username: postgres
  icingaweb.roles.Administrators.groups: Administrators
  icingaweb.roles.Administrators.permissions: '*'
  icingaweb.roles.Administrators.users: icingaadmin

x-icinga2-environment:
  &icinga2-environment
  ICINGA_CN: icinga2
  ICINGA_MASTER: 1

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-file: "10"
    max-size: "1M"

networks:
  default:
    name: icinga-playground

services:
  director:
    command:
      - /bin/bash
      - -ce
      - |
        echo "Testing the database connection. Container could restart."
        (echo > /dev/tcp/icinga-postgres/5432) >/dev/null 2>&1
        echo "Testing the Icinga 2 API connection. Container could restart."
        (echo > /dev/tcp/icinga2/5665) >/dev/null 2>&1
        icingacli director migration run
        (icingacli director kickstart required && icingacli director kickstart run && icingacli director config deploy) || true
        echo "Starting Icinga Director daemon."
        icingacli director daemon run
    entrypoint: []
    logging: *default-logging
    image: icinga/icingaweb2
    restart: on-failure
    volumes:
      - icingaweb:/data:z

  # The Icinga 2 docker image does not support configuration via env vars at the moment.
  # So, we have to ship some configs with this little init container. Referenced in depends_on of the icinga2 service.
  init-icinga2:
    command: [ "/config/init-icinga2.sh" ]
    environment: *icinga2-environment
    image: icinga/icinga2
    logging: *default-logging
    volumes:
      - icinga2:/data:z
      - ./icingadb.conf:/config/icingadb.conf:z
      - ./icingaweb-api-user.conf:/config/icingaweb-api-user.conf:z
      - ./init-icinga2.sh:/config/init-icinga2.sh:z

  icinga2:
    command: [ "sh", "-c", "sleep 5 ; icinga2 daemon" ]
    depends_on:
      - icingadb-redis
      - init-icinga2
    environment: *icinga2-environment
    image: icinga/icinga2
    logging: *default-logging
    ports:
      - 5665:5665
    volumes:
      - icinga2:/data:z
      - ./icinga2.conf.d:/custom_data/custom.conf.d:z

  icingadb:
    environment:
      ICINGADB_DATABASE_TYPE: pgsql
      ICINGADB_DATABASE_HOST: icinga-postgres
      ICINGADB_DATABASE_PORT: 5432
      ICINGADB_DATABASE_DATABASE: icingadb
      ICINGADB_DATABASE_USER: postgres
      ICINGADB_DATABASE_PASSWORD: pgpassword!
      ICINGADB_REDIS_HOST: icingadb-redis
      ICINGADB_REDIS_PORT: 6379
    depends_on:
      - icinga-pgsql
      - icingadb-redis
    image: icinga/icingadb
    logging: *default-logging

  icingadb-redis:
    image: redis
    logging: *default-logging

  icingaweb:
    depends_on:
      - icinga-postgres
    environment:
      icingaweb.enabledModules: director, icingadb, incubator
      <<: [*icinga-db-web-config, *icinga-director-config, *icinga-web-config]
    logging: *default-logging
    image: icinga/icingaweb2
    ports:
      - 8080:8080
    # Restart Icinga Web container automatically since we have to wait for the database to be ready.
    # Please note that this needs a more sophisticated solution.
    restart: on-failure
    volumes:
      - icingaweb:/data:z

  icinga-postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword!
      POSTGRES_MULTIPLE_DATABASES: icingadb,icingaweb,director
    logging: *default-logging
    volumes:
      - ./env/pgsql:/docker-entrypoint-initdb.d:z
      - icingapgdata:/var/lib/postgresql/data:z

volumes:
  icinga2:
  icingaweb:
  icingapgdata:
